name: @name@
version: @version@
main: xyz.novaserver.cutscenes.paper.CutscenesPaper
api-version: 1.19
author: Lui798
depend:
  - ProtocolLib
softdepend:
  - Themis
  - floodgate
  - TAB
  - NovaPlaceholders
commands:
  cutscene:
    description: Manages cutscenes.
    permission: cutscenes.command
permissions:
  cutscenes.command:
    default: op
    description: Gives persmission to /cutscene command